# Generated by Django 5.2.8 on 2025-11-06 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('customer_support', 'Customer Support'), ('sales', 'Sales'), ('technical', 'Technical Support'), ('hr', 'HR'), ('general', 'General Purpose')], default='general', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('training', 'Training')], default='active', max_length=50)),
                ('ai_model', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('claude-3-opus', 'Claude 3 Opus'), ('claude-3-sonnet', 'Claude 3 Sonnet')], default='gpt-3.5-turbo', max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('system_prompt', models.TextField(blank=True, help_text="System prompt to guide the chatbot's behavior")),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chatbots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='projects.project')),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'db_table': 'chatbots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotKnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_links', to='chatbots.chatbot')),
            ],
            options={
                'verbose_name': 'Chatbot Knowledge Base Link',
                'verbose_name_plural': 'Chatbot Knowledge Base Links',
                'db_table': 'chatbot_knowledge_bases',
            },
        ),
    ]
