# Generated by Django 5.2.8 on 2025-11-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotknowledgebase',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_links', to='knowledge_base.knowledgebase'),
        ),
        migrations.AlterUniqueTogether(
            name='chatbotknowledgebase',
            unique_together={('chatbot', 'knowledge_base')},
        ),
    ]
